# Generated by Django 5.0.4 on 2024-04-11 14:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WhatToDo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=500)),
                ('pub_date', models.DateTimeField(verbose_name='data published')),
            ],
        ),
        migrations.CreateModel(
            name='do_type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority', models.IntegerField(choices=[(1, 'Low'), (2, 'Medium'), (3, 'High')], default=2)),
                ('progress', models.CharField(choices=[('Done', 'Done'), ('Doing', 'Doing'), ('DO!', 'Do!')], default='not_start', max_length=10)),
                ('todo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='to_do.whattodo')),
            ],
        ),
    ]
